### PR TITLE
Selenium setup

### PR DESCRIPTION
**Pull request by kahneraja**
Addresses #44

### CODE REVIEW

**Comment by kahneraja** [comment]
To run these tests...
- `npm install`
- `npm run dev`

in a new console....
- `npm run test-ui`

**Comment by samuelcole** [comment]
👍

**Comment by alexyaseen** [comment]
This wants me to install a JDK (which I don't have on this laptop) before running. However, the code looks good to me.

FYI, because we're using React, we actually don't have to use Selenium at all. Using either of these libraries would let us use a regular test framework (Mocha, Ava, etc.) to test UI:
- https://github.com/airbnb/enzyme
- https://facebook.github.io/react/docs/test-utils.html

This PR seems totally fine too, but just thought I'd let you know because the tests can run way faster and be easier to write without relying on Selenium.

**Comment by kahneraja** [comment]
Thanks guys.

I did take a look at enzyme with chai but im wanting to ignore a "unit test" strategy because i find it doesnt cover the orchestration of components.

Given we dont really have much complex unit logic i through getting a real dom with selenium would be more reliable

**Comment by kahneraja** [comment]
Ill add another few more tests, reorganise and submit

**Comment by alexyaseen** [comment]
Got it, makes sense

**Pull request merged**
