### PR TITLE
updated package.json for windows & mac. added npm deploy runner.

### PR DESCRIPTION
**Pull request by kahneraja**

### CODE REVIEW

**Comment by alexyaseen** [comment]
Now it no longer works on Mac. Easy solution I guess would be to have npm run build-mac and npm run build-windows?

**Comment by decause** [comment]
/me uses Linux, so I'm not the one to be testing/commenting on this one. Any updates?

**Comment by alexyaseen** [comment]
`npm run build` looks great for me on mac! `npm run deploy` should make deploying way easier (I haven't tested `npm run deploy` given we need to approve this PR first). We should probably add to readme.md with instructions for deploy, and also a warning not to use unless permission to deploy?

**Comment by kahneraja** [comment]
Cool! Ill close out this one and update the docs. Thanks :)

**Pull request merged**
