### PR TITLE
eslint npm task

### LINKED ISSUE #15: Add npm script to run eslint
npm run lint?

### PR DESCRIPTION
**Pull request by samuelcole**
I also fixed everything I could with `--fix`

fixes #15

### CODE REVIEW

**Comment by alexyaseen** [comment]
+1000

**Comment by kahneraja** [comment]
@samuelcole did a merge from master with my recent changes and cleaned up a few things in search.

still stuck on 2 issues tho...

image

**Comment by samuelcole** [comment]
@kahneraja ah, i think the same change will fix both: instead of using `function (blah) { }` use fat arrows: `blah => { }`

**Comment by kahneraja** [comment]
Ill jump onto this in a few hours if it's not closed :)

**Comment by samuelcole** [comment]
@kahneraja i fixed the lint here: https://github.com/DevProgress/csv-simple-search/commit/157be93d738c16914c871611df12bdbf73e14357

**Pull request merged**
